import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/en/": false,

  "/en/guide/": [
    "introduce",
    {
      text: "Getting started",
      icon: "leibie",
      prefix: "getstarted/",
      collapsible: true,
      children: [
        "start",
        "projectEnv",
        "dataMapping",
        "stringGenerationStrategy",
        "icon",
        "otherConfig",
        "shortcut",
      ],
    },
    "install",
    {
      text: "Features",
      icon: "featuresNew",
      prefix: "features/",
      link: "features/",
      collapsible: true,
      children: [
        "makeIconMove",
        "projectLevelDomainConfig",
        "projectValueConfig",
        "searchEveryWhere",
        "apiGroup",
        "debugApi",
        "downloadApi",
        "stopRequest",
        "navigateCurrentMethod",
        "saveRequest",
        "tempRequest",
        "regenerate",
        "curlImport",
        "copyCurl",
        "copyUrl",
        "apiDocSync",
        "historyRequest",
        "settingManager",
        "fullScreen",
        "annualReport",
        "docAndContact",
        "htmlPreview",
        "swaggerDefaultValueParse",
        "autoDescription",
        "apiList",
        "apiToPostman",
        "apiImportExport",
        "batchExportApiDoc",
        "apiNavigateTree",
        "apiPreview",
        "apiCommentPreview",
        "script",
        "quickAddHeader",
        "headerGroup",
        "jsonGrammarCheck",
      ],
    },
    "script",
    "history",
    "teamwork",
    "buy",
    "versionCompare",
    "concatGroup",
    "faq",
    "priceAdjust",
    "eula",
    "whatsnew",
    "feature",
  ],
});

export const zhSidebar = sidebar({
  "/en/": false,

  "/guide/": [
    {
      text: "课程介绍",
      icon: "leibie",
      prefix: "01Introduction/",
      collapsible: true,
	  link: "/guide/01Introduction",
      children: [
		"01Introduction",
        "02CourseStructure",
      ],
    },
    {
      text: "系统设计面试",
      icon: "featuresNew",
      prefix: "02SystemDesignInterviews/",
      collapsible: true,
      link: "/guide/02SystemDesignInterviews",
      children: [
		"01WhatIsSystemDesignInterview",
        "02HowtoPrepareforSuccess",
		"03HowtoPerformWell"
      ],
    },
  ],
});
